/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dado_rpg;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Matheus Costa
 */
public class MesaDeRpg extends javax.swing.JFrame {
    Dado dadoRpg = new Dado((byte)6);
    /**
     * Creates new form MesaDeRpg
     */
    public MesaDeRpg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Txt_Numero = new javax.swing.JLabel();
        btn_dado6 = new javax.swing.JButton();
        btn_dado8 = new javax.swing.JButton();
        btn_dado10 = new javax.swing.JButton();
        btn_dado12 = new javax.swing.JButton();
        btn_dado16 = new javax.swing.JButton();
        btn_outro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));

        Titulo.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        Titulo.setText("Dado de RPG");

        Txt_Numero.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        Txt_Numero.setText("_");

        btn_dado6.setText("6 Faces");
        btn_dado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dado6ActionPerformed(evt);
            }
        });

        btn_dado8.setText("8 Faces");
        btn_dado8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dado8ActionPerformed(evt);
            }
        });

        btn_dado10.setText("10 Faces");
        btn_dado10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dado10ActionPerformed(evt);
            }
        });

        btn_dado12.setText("12 Faces");
        btn_dado12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dado12ActionPerformed(evt);
            }
        });

        btn_dado16.setText("16 Faces");
        btn_dado16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dado16ActionPerformed(evt);
            }
        });

        btn_outro.setText("Outro");
        btn_outro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Txt_Numero)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addGap(71, 71, 71))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_dado8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dado6, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_dado12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dado10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_dado16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_outro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(Txt_Numero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dado6)
                    .addComponent(btn_dado10)
                    .addComponent(btn_dado16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dado8)
                    .addComponent(btn_dado12)
                    .addComponent(btn_outro))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dado6ActionPerformed
        dadoRpg.setNumeroFacetas((byte)6);
        dadoRpg.sortearNumero();
        byte lucky = dadoRpg.mostrarNumero();
        Txt_Numero.setText(Byte.toString(lucky));
    }//GEN-LAST:event_btn_dado6ActionPerformed

    private void btn_dado8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dado8ActionPerformed
        dadoRpg.setNumeroFacetas((byte)8);
        dadoRpg.sortearNumero();
        byte lucky = dadoRpg.mostrarNumero();
        Txt_Numero.setText(Byte.toString(lucky));
    }//GEN-LAST:event_btn_dado8ActionPerformed

    private void btn_dado10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dado10ActionPerformed
        dadoRpg.setNumeroFacetas((byte)10);
        dadoRpg.sortearNumero();
        byte lucky = dadoRpg.mostrarNumero();
        Txt_Numero.setText(Byte.toString(lucky));
    }//GEN-LAST:event_btn_dado10ActionPerformed

    private void btn_dado12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dado12ActionPerformed
        dadoRpg.setNumeroFacetas((byte)12);
        dadoRpg.sortearNumero();
        byte lucky = dadoRpg.mostrarNumero();
        Txt_Numero.setText(Byte.toString(lucky));
    }//GEN-LAST:event_btn_dado12ActionPerformed

    private void btn_dado16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dado16ActionPerformed
        dadoRpg.setNumeroFacetas((byte)16);
        dadoRpg.sortearNumero();
        byte lucky = dadoRpg.mostrarNumero();
        Txt_Numero.setText(Byte.toString(lucky));
    }//GEN-LAST:event_btn_dado16ActionPerformed

    private void btn_outroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outroActionPerformed
        String outroDado = JOptionPane.showInputDialog("Qual o número de faces do dado?");
        if (outroDado != "" || outroDado != null){
            try{
                byte faces = Byte.parseByte(outroDado);
                dadoRpg.setNumeroFacetas((byte)faces);
                dadoRpg.sortearNumero();
                byte lucky = dadoRpg.mostrarNumero();
                Txt_Numero.setText(Byte.toString(lucky));
            } catch(NumberFormatException n){
                byte faces = 10;
                dadoRpg.setNumeroFacetas((byte)faces);
                dadoRpg.sortearNumero();
                byte lucky = dadoRpg.mostrarNumero();
                Txt_Numero.setText(Byte.toString(lucky));
            }
        }
    }//GEN-LAST:event_btn_outroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesaDeRpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesaDeRpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesaDeRpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesaDeRpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesaDeRpg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Txt_Numero;
    private javax.swing.JButton btn_dado10;
    private javax.swing.JButton btn_dado12;
    private javax.swing.JButton btn_dado16;
    private javax.swing.JButton btn_dado6;
    private javax.swing.JButton btn_dado8;
    private javax.swing.JButton btn_outro;
    // End of variables declaration//GEN-END:variables
}
